image: node:12.22.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn build
  - mv public static && mv build public

  artifacts:
    paths:
    - public
  
  only:
  - main
