image: node:12.22.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - export REACT_APP_API_URL=$API_URL
  - yarn build
  - mv public static && mv build public

  artifacts:
    paths:
    - public
  
  only:
  - main

  environment:
    name: production
    url: https://admin.georgslauf.de
